=== yigudata/MarketDataFetcher/src/cfg/cfg.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v5 rel. 2 U (http://www.xmlspy.com) by cba (cba) -->
<!--W3C Schema generated by XMLSPY v5 rel. 2 U (http://www.xmlspy.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="country">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="exchange" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="required"/>
			<xs:attribute name="enable" type="xs:boolean" use="required"/>
			<xs:attribute name="timezone" type="xs:string" use="optional"/>
			<xs:attribute name="ccy" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="exchange">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="chains" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="chain" maxOccurs="unbounded">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="value" type="xs:string" use="optional"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="supplement_rics" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="ric" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="value" type="xs:string" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="required"/>
			<xs:attribute name="port" type="xs:int" use="required"/>
			<xs:attribute name="enable" type="xs:boolean" use="required"/>
			<xs:attribute name="vola_high" type="xs:float" use="required"/>
			<xs:attribute name="vola_low" type="xs:float" use="required"/>
			<xs:attribute name="open_time_am" type="xs:time" use="required"/>
			<xs:attribute name="close_time_am" type="xs:time" use="required"/>
			<xs:attribute name="open_time_pm" type="xs:time" use="required"/>
			<xs:attribute name="close_time_pm" type="xs:time" use="required"/>
			<xs:attribute name="instruments_file" type="xs:string" use="required"/>
			<xs:attribute name="day_file_path" type="xs:string" use="required"/>
			<xs:attribute name="tick_file_path" type="xs:string" use="required"/>
			<xs:attribute name="hist_file_path" type="xs:string" use="required"/>
			<xs:attribute name="hist_day_file_path" type="xs:string" use="required"/>
			<xs:attribute name="adj_factor_file" type="xs:string" use="required"/>
			<xs:attribute name="timezone" type="xs:string" use="optional"/>
			<xs:attribute name="ccy" type="xs:string" use="optional"/>
			<xs:attribute name="desc" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="global_market_config">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="country" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="eikon_key" type="xs:string" use="required"/>
			<xs:attribute name="holiday_file" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== yigudata/MarketDataFetcher/src/cfg/cfg.xml
<!-- edited with XMLSPY v5 rel. 2 U (http://www.xmlspy.com) by cba (cba) -->
<global_market_config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="cfg.xsd" eikon_key="1361994804e241539daa38ddec1ae67861ff7de5" holiday_file="D:\predator-eagle\global_market\ref\ccy_holiday.csv">
	<country id="CN" enable="true" timezone="Asia/Shanghai" ccy="CNY">
		<exchange id="CCFX" port="6000" enable="true" vola_high="10" vola_low="10" open_time_am="09:30:00" close_time_am="11:30:00" open_time_pm="13:00:00" close_time_pm="15:10:00" instruments_file="D:\predator-eagle\global_market\ref\instruments\cn-ccfx-instrument-list.csv" day_file_path="D:\predator-eagle\global_market\data\dayfile\cn\ccfx\" tick_file_path="D:\predator-eagle\global_market\data\tick\cn\ccfx\" hist_file_path="D:\predator-eagle\global_market\data\hist\cn\ccfx\" hist_day_file_path="D:\predator-eagle\global_market\data\hist_day\cn\ccfx\" adj_factor_file="D:\predator-eagle\global_market\ref\factor\uqer_adj.csv">
			<chains>
				<chain value="0#CIH:"/>
				<chain value="0#CIC:"/>
				<chain value="0#CIF:"/>
			</chains>
			<supplement_rics>
				<ric value="CICc1"/>
				<ric value="CICc2"/>
				<ric value="CICc3"/>
				<ric value="CICc4"/>
				<ric value="CIFc1"/>
				<ric value="CIFc2"/>
				<ric value="CIFc3"/>
				<ric value="CIFc4"/>
				<ric value="CIHc1"/>
				<ric value="CIHc2"/>
				<ric value="CIHc3"/>
				<ric value="CIHc4"/>
				<ric value=".SZSMEPI"/>
				<ric value=".CSI500"/>
				<ric value=".CSI300"/>
				<ric value=".CHINEXTP"/>
			</supplement_rics>
		</exchange>
		<exchange id="XSHG" port="5559" enable="true" vola_high="10" vola_low="10" open_time_am="09:30:00" close_time_am="11:30:00" open_time_pm="13:00:00" close_time_pm="15:10:00" instruments_file="D:\predator-eagle\global_market\ref\instruments\cn-xshg-instrument-list.csv" day_file_path="D:\predator-eagle\global_market\data\dayfile\cn\xshg\" tick_file_path="D:\predator-eagle\global_market\data\tick\cn\xshg\" hist_file_path="D:\predator-eagle\global_market\data\hist\cn\xshg\" hist_day_file_path="D:\predator-eagle\global_market\data\hist_day\cn\xshg\" adj_factor_file="D:\predator-eagle\global_market\ref\factor\uqer_adj.csv"/>
		<exchange id="XSHE" port="5558" enable="true" vola_high="10" vola_low="10"open_time_am="09:30:00" close_time_am="11:30:00" open_time_pm="13:00:00" close_time_pm="15:10:00" instruments_file="D:\predator-eagle\global_market\ref\instruments\cn-xshe-instrument-list.csv" day_file_path="D:\predator-eagle\global_market\data\dayfile\cn\xshe\" tick_file_path="D:\predator-eagle\global_market\data\tick\cn\xshe\" hist_file_path="D:\predator-eagle\global_market\data\hist\cn\xshe\" hist_day_file_path="D:\predator-eagle\global_market\data\hist_day\cn\xshe\" adj_factor_file="D:\predator-eagle\global_market\ref\factor\uqer_adj.csv"/>
		<exchange id="XHKG" port="5557" enable="true" vola_high="10" vola_low="10" open_time_am="09:30:00" close_time_am="12:00:00" open_time_pm="13:00:00" close_time_pm="16:10:00" instruments_file="D:\predator-eagle\global_market\ref\instruments\cn-xhkg-instrument-list.csv" day_file_path="D:\predator-eagle\global_market\data\dayfile\cn\xhkg\" tick_file_path="D:\predator-eagle\global_market\data\tick\cn\xhkg\" hist_file_path="D:\predator-eagle\global_market\data\hist\cn\xhkg\" hist_day_file_path="D:\predator-eagle\global_market\data\hist_day\cn\xhkg\" adj_factor_file="D:\predator-eagle\global_market\ref\factor\xhkg_tr_adj.csv" ccy="HKD">
		<chains>
				<chain value="0#.HSI"/>
			</chains>
			<supplement_rics>
				<ric value=".HSI"/>
			</supplement_rics>
		</exchange>
	</country>
	<country id="US" enable="true" timezone="America/New_York" ccy="USD">
		<!--no lunch break-->
		<exchange id="XNYS" using_index="true" index=".SPX" port="5556" enable="true" vola_high="10" vola_low="10" open_time_am="09:30:00" close_time_am="13:45:00" open_time_pm="13:15:00" close_time_pm="16:10:00" instruments_file="D:\predator-eagle\global_market\ref\instruments\us-xnys-instrument-list.csv" day_file_path="D:\predator-eagle\global_market\data\dayfile\us\xnys\" tick_file_path="D:\predator-eagle\global_market\data\tick\us\xnys\" hist_file_path="D:\predator-eagle\global_market\data\hist\us\xnys\" hist_day_file_path="D:\predator-eagle\global_market\data\hist_day\us\xnys\" adj_factor_file="D:\predator-eagle\global_market\ref\factor\xnys_tr_adj.csv">
		<chains>
				<chain value="0#.SPX"/>
			</chains>
			<supplement_rics>
				<ric value=".SPX"/>
			</supplement_rics>
		</exchange>
	</country>
</global_market_config>
